### ISSUE TITLE
[SB8] "Breadcrumbs" canvas background is not the correct color

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#1367]
In SB7 the background was always gray, to make breadcrumbs visible regardless of the color selected. However, in SB8 the background defaults to white which makes the `white` color option invisible.

![Screenshot 2024-09-13 at 10 44 57 AM](https://github.com/user-attachments/assets/5f7b743a-d373-4fee-a4a5-a34891f847b3)

**Comment by CalebLuster** [comment]
Fixed. This wasn't happening for me but it was happening in the docs preview so I changed it there and that should hopefully resolve it happening in the story as well.

**Comment by Jura** [comment]
@CalebLuster , this is not fixed: https://post-sb8-upgrade-fixes.design-system.pages.dev/?path=/story/components-ui-components-language-switcher--language-switcher-story&args=variant:white&globals=locale:english;backgrounds.grid:!false;backgrounds.value:transparent
